USE master
GO
CREATE DATABASE ArhivskiVjesnik
COLLATE Croatian_CI_AS
GO
USE ArhivskiVjesnik

GO

CREATE TABLE Clanak
(
IDClanak INT CONSTRAINT PK_IDClanak PRIMARY KEY IDENTITY NOT NULL,
Naziv NVARCHAR(150),
Godiste INT,
Volumen INT,
Broj INT,
DatumIzdavanja DATETIME,
DatumObjave DATETIME,
URL NVARCHAR(100)
)

GO

CREATE TABLE Vrsta
(
IDVrsta INT CONSTRAINT PK_IDVrsta PRIMARY KEY IDENTITY NOT NULL,
Naziv NVARCHAR(50)
)

GO

CREATE TABLE Naslov
(
IDNaslov INT CONSTRAINT PK_IDNaslov PRIMARY KEY IDENTITY NOT NULL,
Naziv NVARCHAR(500)
)

GO

CREATE TABLE Sazetak
(
IDSazetak INT CONSTRAINT PK_IDSazetak PRIMARY KEY IDENTITY NOT NULL,
Opis NVARCHAR(MAX)
)

GO

CREATE TABLE Autor
(
IDAutor INT CONSTRAINT PK_IDAutor PRIMARY KEY IDENTITY NOT NULL,
Ime NVARCHAR(50),
Prezime NVARCHAR(50)
)

GO

CREATE TABLE KljucnaRijec
(
IDKljucnaRijec INT CONSTRAINT PK_IDKljucnaRijec PRIMARY KEY IDENTITY NOT NULL,
Vrijednost NVARCHAR(300)
)


GO

CREATE TABLE ClanakVrsta
(
IDClanakVrsta INT CONSTRAINT PK_IDClanakVrsta PRIMARY KEY IDENTITY NOT NULL,
ClanakID INT CONSTRAINT FK_ClanakVrsta_IDClanak FOREIGN KEY REFERENCES Clanak(IDClanak) NOT NULL,
VrstaID INT CONSTRAINT FK_ClanakVrsta_IDVrsta FOREIGN KEY REFERENCES Vrsta(IDVrsta) NOT NULL
)

GO

CREATE TABLE ClanakNaslov
(
IDClanakNaslov INT CONSTRAINT PK_IDClanakNaslov PRIMARY KEY IDENTITY NOT NULL,
ClanakID INT CONSTRAINT FK_ClanakNaslov_IDClanak FOREIGN KEY REFERENCES Clanak(IDClanak) NOT NULL,
NaslovID INT CONSTRAINT FK_ClanakNaslov_IDNaslov FOREIGN KEY REFERENCES Naslov(IDNaslov) NOT NULL
)

GO

CREATE TABLE ClanakSazetak
(
IDClanakSazetak INT CONSTRAINT PK_IDClanakSazetak PRIMARY KEY IDENTITY NOT NULL,
ClanakID INT CONSTRAINT FK_ClanakSazetak_IDClanak FOREIGN KEY REFERENCES Clanak(IDClanak) NOT NULL,
SazetakID INT CONSTRAINT FK_ClanakSazetak_IDSazetak FOREIGN KEY REFERENCES Sazetak(IDSazetak) NOT NULL
)

GO

CREATE TABLE ClanakAutor
(
IDClanakAutor INT CONSTRAINT PK_IDClanakAutor PRIMARY KEY IDENTITY NOT NULL,
ClanakID INT CONSTRAINT FK_ClanakAutor_IDClanak FOREIGN KEY REFERENCES Clanak(IDClanak) NOT NULL,
AutorID INT CONSTRAINT FK_ClanakAutor_IDAutor FOREIGN KEY REFERENCES Autor(IDAutor) NOT NULL
)

GO

CREATE TABLE ClanakKljucnaRijec
(
IDClanakKljucnaRijec INT CONSTRAINT PK_IDClanakKljucnaRijec PRIMARY KEY IDENTITY NOT NULL,
ClanakID INT CONSTRAINT FK_ClanakKljucnaRijec_IDClanak FOREIGN KEY REFERENCES Clanak(IDClanak) NOT NULL,
KljucnaRijecID INT CONSTRAINT FK_ClanakKljucnaRijec_IDKljucnaRijec FOREIGN KEY REFERENCES KljucnaRijec(IDKljucnaRijec) NOT NULL
)

GO